"""empty message

Revision ID: e1ee10ea7eed
Revises: d4e9f56d660e
Create Date: 2016-07-11 16:31:59.790490

"""

# revision identifiers, used by Alembic.
revision = 'e1ee10ea7eed'
down_revision = 'd4e9f56d660e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('ename', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_users_ename'), 'users', ['ename'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_ename'), table_name='users')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'ename')
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
